### ISSUE TITLE
Any Identifiable Info & Advantage of uber-apk-signer vs Openssl?

### ISSUE THREAD

**Issue by 0pLuS0** [patrickfav/uber-apk-signer#13]
Hello,

Is there anything when signing certs that can be identified back to the person, or computer, etc., that can identify where it comes from?

From my understanding no, it's only what information someone puts in/creates... The owner/issuer O= L= ST= C= etc...

Nice app you created too...

But in Linux I just do all this by hand, so is there really any advantage to using uber-apk-signer over signing my own in Linux like the below?

mkdir -p /etc/ssl/localcerts

Run cmds in /localcerts

openssl genrsa -out key.pem 1024
openssl req -new -key key.pem -out request.pem
openssl x509 -req -days 9999 -in request.pem -signkey key.pem -out certificate.pem
openssl pkcs8 -topk8 -outform DER -in key.pem -inform PEM -out key.pk8 -nocrypt

java -jar signapk.jar /etc/ssl/localcerts/certificate.pem /etc/ssl/localcerts/key.pk8 framework-res.apk test.apk

THANKS

**Comment by 0pLuS0** [comment]
Forgot to mention also verify show;

Expires: Thu Mar 10 10:10:05 GMT 2044

Sorry for my ignorance in all this, I'm assuming it's only showing for me locally that GMT isn't going to be in the file for everyone to see?

Thanks

**Comment by patrickfav** [comment]
> From my understanding no, it's only what information someone puts in/creates... The owner/issuer O= L= ST= C= etc...

If you do not publish your certificate, I would agree that the only identifying information is provided in the cert. Why do you worry about beieng identified?

> But in Linux I just do all this by hand, so is there really any advantage to using uber-apk-signer over signing my own in Linux like the below?

I use Google's apk-signer in the background, which uses (I think) a proprietary signing protocol (https://source.android.com/security/apksigning/v2) which I don't think is supported by other tools outside of Android. The advantage of this tool is just convenience over using `apk-signer` itself https://developer.android.com/studio/command-line/apksigner

**Comment by 0pLuS0** [comment]
Ok I wasn't sure if anything else was embedded, I assumed these show everything there is to see;

keytool -printcert -file CERT.RSA
keytool -list -printcert -jarfile framework-res.apk

Thanks
