### ISSUE TITLE
Request: Ablity to change Owner/Issuer Names

### ISSUE THREAD

**Issue by 0pLuS0** [patrickfav/uber-apk-signer#15]
Hello,

Can you please make it so we can change all fields for the Owner/Issuer?

Owner: CN=Android Debug, OU=Android, O=US, L=US, ST=US, C=US
Issuer: CN=Android Debug, OU=Android, O=US, L=US, ST=US, C=US

Thanks

**Comment by 0pLuS0** [comment]
Ahh ok, I didn't know if others could be created with uber-apk-signer, hmm would this be advantageous to have the ability with uber-apk-signer?

Thanks

**Comment by patrickfav** [comment]
> if others could

If others what?

**Comment by 0pLuS0** [comment]
Well I'm assuming I clearly don't know what I'm doing... LOL

I thought it would be advantageous to have more then just the debug cert, and also have the ability to make all of the sections for Owner/Issuer what we want.

I guess I'm clearly not seeing why this ability can't exist to either go with the default debug, or choose...

Sorry if I'm being dense here...

Thanks

**Comment by patrickfav** [comment]
> I thought it would be advantageous to have more then just the debug cert, and also have the ability to make all of the sections for Owner/Issuer what we want.

The debug certificate is a constant. If you change the debug certificate, it won't be recognized as such, making it effectively a very bad release certificate. I also don't see the use case for having a debug certificate with different owner/issuer properties?

I'll close this issue, as it does not really discusses issues with this very tool.

Cheers.

**Comment by 0pLuS0** [comment]
Sorry for confusion, I meant to have the ability to use a difference cert, besides just debug, with the ability someone can sign with their Owner/Issuer information they choose is all...

Thanks
