### ISSUE TITLE
Support APK Signing Schema v3

### ISSUE THREAD

**Issue by patrickfav** [patrickfav/uber-apk-signer#18]
Since Android 9 key rotation is supported: https://source.android.com/security/apksigning/v3

**Comment by patrickfav** [comment]
Released in v1.1.0

**Comment by phamquangbaoplus** [comment]
I used Embedded debug.keystore inside the tool. Update to the latest version 1.1.0 will break old users from update APK or not?

**Comment by patrickfav** [comment]
No I don't see why it should. The new v3 schema is only different when migrating signatures.

**Comment by patrickfav** [comment]
You could, of course, continue to use v1.0.0

**Comment by phamquangbaoplus** [comment]
Hello, I have another question.

Can you please add option allow using the built-in keystore although another key exist in user_home/.android
