### ISSUE TITLE
Error: Unable to access jarfile uber-apk-signer.jar

### ISSUE THREAD

**Issue by pretech86** [patrickfav/uber-apk-signer#19]
root@kali:~/Downloads/android/uber-apk-signer# java -jar uber-apk-signer.jar --apks /root/Downloads/android/facebook.apk

Error: Unable to access jarfile uber-apk-signer.jar

can you help me please

**Comment by Radiation-Redefined** [comment]
i am facing same issue how did u fix it

**Comment by ihorBielovol** [comment]
I have this problem too.
