### ISSUE TITLE
Add option allow using the built-in keystore even another key exist in user_home/.android

### ISSUE THREAD

**Issue by phamquangbaoplus** [patrickfav/uber-apk-signer#20]
Hello, I have another question.

Can you please add option allow using the built-in keystore even another key exist in user_home/.android. I don't want to use the key in user_home/.android.

Because I sign apk using the built-in keystore and now after I installed Android Studio, it break the old sign.

**Comment by patrickfav** [comment]
Not sure what you mean with "built-in keystore" not referring to the one in your `.android` home dir. However you can provide any keystore (debug or release) with the cli parameters:

```
--ksDebug <keystore>           Same as --ks parameter but with a debug keystore. With this option the
                                  default keystore alias and passwords are used and any arguments relating
                                  to these parameter are ignored.
```

Check out the Readme.md, I think it is described quite thoroughly.

**Comment by phamquangbaoplus** [comment]
> Not sure what you mean with "built-in keystore" not referring to the one in your `.android` home dir. However you can provide any keystore (debug or release) with the cli parameters:
> 
> ```
> --ksDebug <keystore>           Same as --ks parameter but with a debug keystore. With this option the
>                                   default keystore alias and passwords are used and any arguments relating
>                                   to these parameter are ignored.
> ```
> 
> Check out the Readme.md, I think it is described quite thoroughly.

built-in keystore is the keystore you put inside the tool. It using that key if the is no key is provided.

I want using that key

But I have Android Studio installed so the tool using the key in C:\Users\User\.android\debug.keystore 

I don't want .android\debug.keystore so can you add option to sign with the built-in keystore?

**Comment by phamquangbaoplus** [comment]
Hi,

I have a solution for that.

Unzip uber-apk-signer.jar then get the debug.keystore in side that.

Then run with --ksDebug debug.keystore 

Thanks for your help.

**Comment by patrickfav** [comment]
A I totally forgot I added an embedded keystore :) You can of course repackage the jar with your own keystore but it is way easier to just provide the path to one with the cli option I showed you earlier. There is even an example in the Readme:

> Provide your own location of your debug keystore

    java -jar uber-apk-signer.jar -a /path/to/apks --ksDebug /path/debug.jks

**Comment by patrickfav** [comment]
It seems there is no new info.

**Comment by imyxh** [comment]
I think the requested feature was to have a flag, e.g. `--ksEmbedded`, to *force use of the embedded keystore* even if a user's keystore is found in `~/.android`. 

Edit: I was gonna submit a PR to add this but actually found that the default behavior seems to use the embedded keystore anyway, even though `~/.android/debug.keystore` exists? /shrug
