### ISSUE TITLE
zipalign not compressing

### ISSUE THREAD

**Issue by MEGAMINDMK** [patrickfav/uber-apk-signer#27]
zipalign not compressing as 
(java -jar uber-apk-signer.jar -a apk/app-release-unsigned.apk --out release)

C:\cordova\Android\android-sdk\build-tools\29.0.3\zipalign -v 4 app-release-unsigned.apk appname.apk
where app-release-unsigned.apk contains 265kb when it gets compressed it gets appname.apk 258kb

**Comment by patrickfav** [comment]
Why should zip**align** compress? It only aligns bytes in a way so that APKs can better access their content:

>  The purpose is to ensure that all uncompressed data starts with a particular alignment relative to the start of the file. Specifically, it causes all uncompressed data within the APK, such as images or raw files, to be aligned on 4-byte boundaries. This allows all portions to be accessed directly with mmap() even if they contain binary data with alignment restrictions. The benefit is a reduction in the amount of RAM consumed when running the application.

https://developer.android.com/studio/command-line/zipalign

**Comment by MEGAMINDMK** [comment]
Thats the thing, why did it used to conlress my apps before but doesnt conlress with ur cli tool

**Comment by patrickfav** [comment]
Zipaligning and Signing can slightly change the APK size (kb), but the compression is due to the APK format itself (its basically a zip). Unfortunately I'm not sure what you mean.

**Comment by MEGAMINDMK** [comment]
hey hi, nice to see your reply. the thing is i use cordova and it has something  like zipalign -v 4 which aligns the app and compresses even more , but with ur method the code ziplalign -v 4 doesnt work

**Comment by patrickfav** [comment]
Hey, so as I wrote earlier, zipalign is _not_ a compression technique - any change in output size is due to aligning it within the zip align, not a result of compression. It could be that you did not do signing v2, which adds a couple of kbs to the APKs, which this cli does by default.
