### ISSUE TITLE
Good APK but can't verify signature

### ISSUE THREAD

**Issue by JustDragon** [patrickfav/uber-apk-signer#3]
This is apk http://www45.zippyshare.com/v/B8jwSOrZ/file.html. I can install it fine but when run with -y verifyOnly, i get this error.

> - zipalign verified
        - signature VERIFY FAILED (Unknown Heroes_v1.0.1.apk)
                ERROR: JAR signer UNKNOWNH.RSA: Failed to verify JAR signature META-INF/UNKNOWNH.RSA against META-INF/UNKNOWNH.SF: java.security.SignatureException: Algorithm constraints check failed on disabled algorithm: MD5.

**Comment by patrickfav** [comment]
Seems that it is signed with on older method? It says

>  java.security.SignatureException: Algorithm constraints check failed on disabled algorithm: MD5

If you sign it with the tool, it should verify ok?

**Comment by JustDragon** [comment]
Yes, if signed with your tool, can verify ok. But I want to view this apk signature. Can you please show me how? Thank you!

**Comment by patrickfav** [comment]
Use `--verbose ` to see more output when verifingy. See here https://stackoverflow.com/a/40064199/774398 on how to sign/verify with original tools.

**Comment by JustDragon** [comment]
I get this error. Do you know how to fix it?
ERROR: JAR signer UNKNOWNH.RSA: Failed to verify JAR signature META-INF/UNKNOWNH.RSA against META-INF/UNKNOWNH.SF: java.security.SignatureException: Algorithm constraints check failed on disabled algorithm: MD5.

**Comment by patrickfav** [comment]
Again, I think your signing method uses old algorithms (e.g. MD5 hashes, which might be deprecated)

**Comment by JustDragon** [comment]
Ok, thank you!
