### ISSUE TITLE
Curious question: how is Uber related to this repo?

### ISSUE THREAD

**Issue by fzyzcjy** [patrickfav/uber-apk-signer#32]
Hi thanks for the repo! I wonder how is Uber related to it? AFAIK Uber is a company, so I guess it is a product of the company? But I do not see anything in README

**Comment by renatofrota** [comment]
References:
https://www.google.com/search?q=define:uber
https://en.wiktionary.org/wiki/uber

**Comment by patrickfav** [comment]
Fun fact: "uber" is derived from the german word "über" wich basically means "above".

> The crossover of the term "über" from German into English goes back to the work of German philosopher Friedrich Nietzsche. In 1883, Nietzsche coined the term "Übermensch" to describe the higher state to which he felt men might aspire. The term was brought into English by George Bernard Shaw in the title to his 1903 play Man and Superman. During his rise to power, Adolf Hitler adopted Nietzsche's term, using it in his descriptions of an Aryan master race.

https://en.wikipedia.org/wiki/%C3%9Cber#In_English
