### ISSUE TITLE
How do I skip the VERIFY process?

### ISSUE THREAD

**Issue by iAndyHD3** [patrickfav/uber-apk-signer#33]
I'd like to skip this verification, is it possible?

![image](https://user-images.githubusercontent.com/54410739/152635641-5a18e35b-3107-4c03-896e-0d1e16790cf2.png)

 It seems like its not possible because it is not in the help command but I'll ask anyway just in case

**Comment by iAndyHD3** [comment]
While developing my project I have to sign the apk a lot of times to debug (50 times a day or more) and I just want my compiling script to be faster. Its a bit annoying because I have to close the cmd window manually each single time when the verification process starts. I would like to verify only for release versions, for debugging something like `--skipVerify` would be great

**Comment by patrickfav** [comment]
Ah I understand. This tool was developed for release use cases, thinking that debugging would most often probably be done by Android Studio (which is then faster & more convenient)
