### ISSUE TITLE
Zipalign problem | Linux

### ISSUE THREAD

**Issue by Morsmalleo** [patrickfav/uber-apk-signer#34]
So basically my problem is this.

On the README.md it says that there is a built in zipalign feature, however when I use uber-apk-signer on Linux to try and sign an apk, I can't sign an APK at all because because `zipalign could not execute`, if I run `apt install zipalign` however, it works, how do I utilise the built-in zipalign feature if it's possible???

Sorry I'm still very new to this repo, I used to use an older type of signer but this one is better.

**Comment by siloed** [comment]
hey, i had the same prob, and I dont think this package eitehr comes with its own zipalign as it says or its somehow broken. i tried installing zipalign via apt and while it installs, if you just run command: zipalign, you will see it's giving out errors. I found you need to copy a different 'libbacktrace.so.0' from https://packages.debian.org/buster/android-libbacktrace to make it work.

the following solution worked for me nicely. hope it helps:
https://superuser.com/questions/1614228/zipalign-symbol-lookup-error-usr-lib-x86-64-linux-gnu-android-libbacktrace-so

**Comment by Morsmalleo** [comment]
> hey, i had the same prob, and I dont think this package eitehr comes with its own zipalign as it says or its somehow broken. i tried installing zipalign via apt and while it installs, if you just run command: zipalign, you will see it's giving out errors. I found you need to copy a different 'libbacktrace.so.0' from https://packages.debian.org/buster/android-libbacktrace to make it work.
> 
> the following solution worked for me nicely. hope it helps: https://superuser.com/questions/1614228/zipalign-symbol-lookup-error-usr-lib-x86-64-linux-gnu-android-libbacktrace-so

I will certainly look into this

**Comment by Morsmalleo** [comment]
Ok so I've got an update, it seems 32bit Linux based Operating Systems have this problem because testing on a 64bit Linux VM the zipalign feature works fine without the need to install it via `apt`, different for 32bit Linux based OS's, I searched the README.md again and had a complete FOREHEAD SMACK moment 😂

It's stated in the README.md that

"Currently on Linux 32bit: zipalign must be set in PATH"

Hence why the zipalign feature works after an `apt install` on 32but Linux
