### ISSUE TITLE
Zipalign problem | windows 11

### ISSUE THREAD

**Issue by Zhanghao0150** [patrickfav/uber-apk-signer#37]
SIGN
file: D:\work\android\rebuild\tsxk_shiguanghb_online_4149_220721\dist\tsxk_220721.apk (2160.73 MiB)
checksum: e67c8bad5b9263816b91ab55fcada97ab65b3203498e5782ea63a9c14f1041c3 (sha256)
- could not align
could not execute zipalign
Run with '--debug' parameter to get additional information.

**Comment by patrickfav** [comment]
Try to put zipalign.exe in your path and read the docs on how to use it.

**Comment by myzhan** [comment]
Related issue
https://stackoverflow.com/questions/74918336/zipalign-exe-does-not-work-on-windows-for-apks-that-are-larger-than-2gb
