### ISSUE TITLE
INSTALL_FAILED_UPDATE_INCOMPATIBLE

### ISSUE THREAD

**Issue by iddq** [patrickfav/uber-apk-signer#38]
APK cannot be installed after resign.

java -jar uber-apk-signer-1.2.1.jar --allowResign  -a

adb install -r
Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE]

**Android 6.0.1**

for first look the original APK contains CERT.SF and CERT.RSA

**Comment by patrickfav** [comment]
As @MarcMil already stated, uninstall the app first. Then install with the new certificate - this is by design and a security measure of Android.

**Comment by iddq** [comment]
On older android systems like 6.0.1, uninstalling the app from GUI is not enough. We have to uninstall it by adb uninstall command even that is uninstalled from GUI before because the certificate somehow remains on the system.
