### ISSUE TITLE
Error: Unable to access jarfile uber-apk-signer.jar

### ISSUE THREAD

**Issue by HyperSilver69** [patrickfav/uber-apk-signer#46]
This has been asked twice but both have been marked as "Completed" Without explaining how it was fixed. any help?
![afbeelding](https://user-images.githubusercontent.com/91153148/230877146-ae054fde-d4bd-4c8d-aced-027b56abe2be.png)

**Comment by HyperSilver69** [comment]
Closed, fixed. If anyone is getting this error, make sure the APK is called `uber-apk-signer.jar` and doesn't have the version behind it.

**Comment by kauemurakami** [comment]
Any solution for this today? the error persists
