### ISSUE TITLE
Sign with v1 only?

### ISSUE THREAD

**Issue by libYo** [patrickfav/uber-apk-signer#5]
How can i sign app v1, is support only v2?

**Comment by patrickfav** [comment]
The tool supports v1, but not explicitly. I use the[ apksigner from Google](https://developer.android.com/studio/command-line/apksigner.html) which automatically decideds which signing scheme is the best possible supported according to your APK's minSdk:

> --v1-signing-enabled <true | false>
> Determines whether apksigner signs the given APK package using the traditional, JAR-based signing scheme. By default, the tool uses the values of --min-sdk-version and --max-sdk-version to decide when to apply this signature scheme.
> 
> --v2-signing-enabled <true | false>
> Determines whether apksigner signs the given APK package using the APK Signature Scheme v2. By default, the tool uses the values of --min-sdk-version and --max-sdk-version to decide when to apply this signature scheme.

This should give you always the best compatibility and security automatically
