### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by yihongyuelan** [patrickfav/uber-apk-signer#7]
command will cause NullPointerException as below:
java -jar uber-apk-signer.jar --apks test_unsigned.apk

And I add a pull reques https://github.com/patrickfav/uber-apk-signer/pull/6/commits/667947646f19da3b1a31dc1c8b59bccedf9bcb68

**Comment by patrickfav** [comment]
I merged the PR and will write a unit test. If everything works fine, I'll make a release. Thanks again

**Comment by Surendrajat** [comment]
I'm facing same issue hrere. Please update release.

**Comment by patrickfav** [comment]
Fixed in v0.8.4

https://github.com/patrickfav/uber-apk-signer/releases/tag/v0.8.4
