### ISSUE TITLE
Can you please sign this apk file for me ?

### ISSUE THREAD

**Issue by hillz2** [patrickfav/uber-apk-signer#9]
My internet is really slow and I have been trying to clone your git repo but fails every time, can you please help me sign this apk file for me ? Here's the file: https://www.dropbox.com/s/5j4mikcft3m4qic/com.lazada.android.apk?dl=0

Just sign it and then upload it somewhere else, thank you.

**Comment by Surendrajat** [comment]
Here is your signed app on [GDrive](https://drive.google.com/open?id=19uLj1M-ORr6zckDs0H_KkfEDjuhz_xlP).
However you only need to download this [uber-apk-signer.jar file](https://github.com/patrickfav/uber-apk-signer/releases/download/v0.8.4/uber-apk-signer-0.8.4.jar) to sign apk not the whole repository.

**Comment by hillz2** [comment]
Thanks
